kafka:
  image: antlypls/kafka
  environment:
    - KAFKA=localhost:9092
    - ZOOKEEPER=localhost:2181
  expose:
    - "2181"
    - "9092"

spark:
  image: antlypls/spark
  command: bash
  volumes:
    - ./target/scala-2.10:/app
  links:
   - kafka
